### ISSUE TITLE
怎么加longtap（长按）事件？

### ISSUE THREAD

**Issue by datura-lj** [yanghuiLu/previewImage-mobile#2]
怎么在长按图片时候，加一个保存到相册功能？求教，我的思路是加个定时器模拟，然后调一个回调函数。

**Comment by yanghuiLu** [comment]
touchstart的时候setTimeout调用保存相册功能，touchend的时候clearTimeout

**Comment by datura-lj** [comment]
恩，我就是这么加的，但是怎么才能把，index传递出去呢？我考虑的是存到cookie中

**Comment by yanghuiLu** [comment]
你们没有固定跟原生应用通讯的api么？如果是嵌入原生应用的html5页面，ios和安卓那边都可以提供通讯api的

**Comment by datura-lj** [comment]
有的，不过保存相册的页面要我们写。

**Comment by yanghuiLu** [comment]
@datura-lj 你只要传递给他们需要保存的图片url就可以了

**Comment by datura-lj** [comment]
是这样的，方便加您一下嘛？59720607

**Comment by yanghuiLu** [comment]
@datura-lj 加了
